<?php
/**
 * Created by PhpStorm.
 * User: csm
 * Date: 25/10/18
 * Time: 09:50
 */
?>
@extends("layouts.pdf")
@section("title", "Invoice")
@section("description", "Invoice to Kuali")
@push("css")
    <style>
        #table-wrapper {
            overflow: visible !important;
        }
    </style>
@endpush
{{--@section("addressee", "Emirand Enterprises Ltd.")--}}
@section('report-details')
    <div class="row border border-bottom">
        <div class="col-4" id="table-wrapper">
            <table class="table table-condensed">
                <tbody class="">
                <tr class="border">
                    <th class="border">Invoice No.</th>
                    <td class="border text-right">{{$invoice->invoice_number}}</td>
                </tr>
                <tr>
                    <th class="border">Supplier.</th>
                    <td class=" border text-right"><span style="font-weight: bolder;">{{$invoice->supplier->name }}</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-4" id="table-wrapper">
            {{--<table class="table table-condensed">
                <tbody class="">
                <tr>
                    <th class="border">Ordered By.</th>
                    <td class=" border text-right">{{$invoice->creator->name}}</td>
                </tr>
                <tr class="border">
                    <th class="border">Order Date.</th>
                    <td class="border text-right">{{\Carbon\Carbon::parse($invoice->ordered_at)}}</td>
                </tr>
                </tbody>
            </table>--}}
        </div>
        <div class="col-4" id="table-wrapper">
            <table class="table table-condensed">
                <tbody class="">
                <tr>
                    <th class="border">Generated By:</th>
                    <td class=" border text-right">{{$invoice->creator->name}}</td>
                </tr>
                <tr class="border">
                    <th class="border">Invoice Date:</th>
                    <td class="border text-right">{{\Carbon\Carbon::parse($invoice->invoiced_at)}}</td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
@stop
@section('report-body')
    <table class="table table-bordered table-striped table-condensed">
        <tbody>
        <tr>
            <th>Delivery Date</th>
            <th>Delivery Note</th>
            <th>GRN No.</th>
            <th>Gross Amt</th>
            <th>Discount</th>
            <th>Net Amount</th>
            <th>V.A.T</th>
            <th>Total Amount</th>
        </tr>
        @php
            $net_total = 0;
            $grand_total = 0;
            $vat_total = 0;
        @endphp
        @foreach($invoice->grns as $grn)
            @php
                $grn->net_total = $grn->gross_total - $grn->discount_total;
                $grn->grand_total = $grn->net_total + $grn->vat_total;
                //Totals
                $net_total      +=  $grn->net_total;
                $grand_total    +=  $grn->grand_total;
                $vat_total      +=  $grn->vat_total;
            @endphp
        <tr>
            <td>{{\Carbon\Carbon::parse($grn->received_at)}}</td>
            <td class="">{{$grn->delivery_note}}</td>
            <td class="">{{$grn->grn_number}}</td>
            <td class="text-right">{{number_format($grn->gross_total , 2)}}</td>
            <td class="text-right">{{number_format($grn->discount_total , 2)}}</td>
            <td class="text-right">{{number_format($grn->net_total , 2)}}</td>
            <td class="text-right">{{number_format($grn->vat_total,2)}}</td>
            <td class="text-right">{{number_format($grn->grand_total,2)}}</td>
        </tr>
        @endforeach
        </tbody>
    </table>
@stop
@section('report-footer')
    <div class="row">
        <div class="col-8"></div>
        <div class="col-4">
            <table class="table table-borderless" style="border-top: double !important;">
                <tr class="mb-0 p-0">
                    <th>Net Total:</th>
                    <th class="text-right bold">{{number_format($net_total,2)}}</th>
                </tr>
                <tr class="mb-0 p-0">
                    <th>V.A.T Total:</th>
                    <th class="text-right bold">{{number_format($vat_total,2)}}</th>
                </tr>
                <tr class="border-top" style="border-bottom: 1px solid black;">
                    <th>Grand Total:</th>
                    <th class="text-right bold">{{number_format($grand_total, 2)}}</th>
                </tr>
            </table>
        </div>
    </div>
@stop
